[package]
name = "ryni"
version = "0.2.1"
edition = "2024"
repository = "https://github.com/computerlovetech/ryni"
description = "A harness linter, written in Rust"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_yaml_ng = "0.10"
walkdir = "2"
pulldown-cmark = "0.13"
percent-encoding = "2"
annotate-snippets = "0.12.16"

[dev-dependencies]
tempfile = "3"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
